trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: Install dependencies

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure-CICD-ServiceConnection'
    appType: 'webAppLinux'
    appName: 'Azure-CICD-ServiceConnection'
    package: '.'